services:
  - type: web
    name: researchpeps-backend
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUBLIC_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: ADMIN_EMAILS
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false